server:
  port: 8080

logging:
  level:
    org:
      springframework:
        data:
          neo4j: DEBUG

spring:
  application:
    name: product-service-api
  jpa:
    generate-ddl: true
  data:
    neo4j:
      database: neo4j
  neo4j:
    uri: neo4j://localhost:7687
    authentication:
      username: neo4j
      password: admin
  redis:
    host: localhost
    port: 6379
    connect-timeout: 60
    database: 0



